// The Ruby Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker <jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Updated 2025 for modern Ruby (Ruby 3.3)

#include "langruby.h"

LangRuby ::LangRuby() {

	fill();
	init_switches();

	doSymbols  = Yes;
	doScalars  = Yes;
	doArrays   = Yes;
	doHashes   = Yes;
	doUnxComnt = Yes;
}

void LangRuby ::fill() {

	// Ruby 3.3 keywords
	string K[] = {
		"BEGIN",
		"END",
		"__ENCODING__",
		"__FILE__",
		"__LINE__",
		"alias",
		"and",
		"begin",
		"break",
		"case",
		"class",
		"def",
		"defined",
		"do",
		"else",
		"elsif",
		"end",
		"ensure",
		"false",
		"for",
		"if",
		"in",
		"module",
		"next",
		"nil",
		"not",
		"or",
		"raise",
		"redo",
		"rescue",
		"retry",
		"return",
		"self",
		"super",
		"then",
		"true",
		"undef",
		"unless",
		"until",
		"when",
		"while",
		"yield",
	};
	for(int k=0;k < 42;k++) {keys.push_back(K[k]);}

	// Ruby 3.3 built-in types and core classes
	string T[] = {
		"Array",
		"BasicObject",
		"Comparable",
		"Complex",
		"Data",
		"Enumerable",
		"Enumerator",
		"Fiber",
		"Float",
		"Hash",
		"Integer",
		"IO",
		"Kernel",
		"Method",
		"Mutex",
		"NilClass",
		"Numeric",
		"Object",
		"Proc",
		"Process",
		"Queue",
		"Ractor",
		"Range",
		"Rational",
		"Regexp",
		"Set",
		"String",
		"Struct",
		"Symbol",
		"Thread",
		"Time",
		"TrueClass",
		"FalseClass",
	};
	for(int t=0;t < 33;t++) {types.push_back(T[t]);}
}

