// The Modula2 Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Updated 2025 for ISO Modula-2 and Modula-2 R10

#include "langmodula.h"

LangModula2 ::LangModula2() {

	fill();
	init_switches();

	doPasComnt = Yes;
}

void LangModula2 ::fill() {

	// Modula-2 keywords (ISO 10514 and R10)
	string K[] = {
		"ABSTRACT",
		"ALIAS",
		"AND",
		"ARGLIST",
		"BEGIN",
		"BLUEPRINT",
		"BY",
		"CASE",
		"CLASS",
		"CLOSE",
		"CONST",
		"COPY",
		"DEFINITION",
		"DEFER",
		"DIV",
		"DO",
		"ELSE",
		"ELSIF",
		"END",
		"EXCEPT",
		"EXIT",
		"EXPORT",
		"FINALLY",
		"FOR",
		"FORWARD",
		"FROM",
		"GENERIC",
		"GENLIB",
		"GUARD",
		"IF",
		"IMPLEMENTATION",
		"IMPORT",
		"IN",
		"LOOP",
		"MOD",
		"MODULE",
		"NEW",
		"NONE",
		"NOT",
		"OF",
		"OPAQUE",
		"OR",
		"PACKEDSET",
		"POINTER",
		"PROCEDURE",
		"QUALIFIED",
		"READ",
		"REFERENTIAL",
		"RELEASE",
		"REM",
		"REPEAT",
		"RETAIN",
		"RETRY",
		"RETURN",
		"REVEAL",
		"SET",
		"THEN",
		"TO",
		"TRACED",
		"TYPE",
		"UNQUALIFIED",
		"UNTIL",
		"VAR",
		"WHILE",
		"WITH",
		"WRITE",
		"YIELD",
	};
	for(int k=0;k < 67;k++) {keys.push_back(K[k]);}

	// Modula-2 types (ISO 10514 and R10)
	string T[] = {
		"ACHAR",
		"ADDRESS",
		"ARRAY",
		"BITSET",
		"BOOLEAN",
		"BYTE",
		"CARDINAL",
		"CHAR",
		"COMPLEX",
		"FALSE",
		"INTEGER",
		"LOC",
		"LONGCARD",
		"LONGCOMPLEX",
		"LONGINT",
		"LONGREAL",
		"NIL",
		"OCTET",
		"PROC",
		"PROTECTION",
		"REAL",
		"RECORD",
		"SHORTCARD",
		"SHORTINT",
		"SHORTREAL",
		"TRUE",
		"UCHAR",
		"UNICHAR",
		"WORD",
	};
	for(int t=0;t < 29;t++) {types.push_back(T[t]);}
}
