// The VHDL Language definition file for Web C Plus Plus
// Generated by Thomas Hedler<thomas.hedler@fen-net.de> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Updated 2025 for VHDL-2019 (IEEE 1076-2019)

// Very High Speed Integrated Circuit Hardware Description Language

#include "langvhdl.h"

LangVHDL ::LangVHDL() {

	fill();
	init_switches();

	doCaseKeys  = No;   // VHDL is case-insensitive
	doLabels    = Yes;
	doAdaComnt  = Yes;  // -- line comments
	doSymbols   = Yes;
}

void LangVHDL ::fill() {

	// VHDL-2019 reserved words (IEEE 1076-2019)
	string K[] = {
		"ABS",
		"ACCESS",
		"AFTER",
		"ALIAS",
		"ALL",
		"AND",
		"ARCHITECTURE",
		"ARRAY",
		"ASSERT",
		"ATTRIBUTE",
		"BEGIN",
		"BLOCK",
		"BODY",
		"BUFFER",
		"BUS",
		"CASE",
		"COMPONENT",
		"CONFIGURATION",
		"CONSTANT",
		"CONTEXT",
		"DEFAULT",
		"DISCONNECT",
		"DOWNTO",
		"ELSE",
		"ELSIF",
		"END",
		"ENTITY",
		"EXIT",
		"FILE",
		"FOR",
		"FORCE",
		"FUNCTION",
		"GENERATE",
		"GENERIC",
		"GROUP",
		"GUARDED",
		"IF",
		"IMPURE",
		"IN",
		"INERTIAL",
		"INOUT",
		"IS",
		"LABEL",
		"LIBRARY",
		"LINKAGE",
		"LITERAL",
		"LOOP",
		"MAP",
		"MOD",
		"NAND",
		"NEW",
		"NEXT",
		"NOR",
		"NOT",
		"NULL",
		"OF",
		"ON",
		"OPEN",
		"OR",
		"OTHERS",
		"OUT",
		"PACKAGE",
		"PARAMETER",
		"PORT",
		"POSTPONED",
		"PRIVATE",
		"PROCEDURE",
		"PROCESS",
		"PROTECTED",
		"PURE",
		"RANGE",
		"RECORD",
		"REGISTER",
		"REJECT",
		"RELEASE",
		"REM",
		"REPORT",
		"RETURN",
		"ROL",
		"ROR",
		"SELECT",
		"SEVERITY",
		"SIGNAL",
		"SHARED",
		"SLA",
		"SLL",
		"SRA",
		"SRL",
		"SUBTYPE",
		"THEN",
		"TO",
		"TRANSPORT",
		"TYPE",
		"UNAFFECTED",
		"UNITS",
		"UNTIL",
		"USE",
		"VARIABLE",
		"VIEW",
		"WAIT",
		"WHEN",
		"WHILE",
		"WITH",
		"XNOR",
		"XOR",
	};
	for(int k=0;k < 104;k++) {keys.push_back(K[k]);}

	// VHDL predefined types from package std.standard and ieee libraries
	string T[] = {
		"BIT",
		"BIT_VECTOR",
		"BOOLEAN",
		"BOOLEAN_VECTOR",
		"CHARACTER",
		"DELAY_LENGTH",
		"FILE_OPEN_KIND",
		"FILE_OPEN_STATUS",
		"INTEGER",
		"INTEGER_VECTOR",
		"NATURAL",
		"POSITIVE",
		"REAL",
		"REAL_VECTOR",
		"SEVERITY_LEVEL",
		"SIGNED",
		"STD_LOGIC",
		"STD_LOGIC_VECTOR",
		"STD_ULOGIC",
		"STD_ULOGIC_VECTOR",
		"STRING",
		"TEXT",
		"TIME",
		"TIME_VECTOR",
		"UNSIGNED",
	};
	for(int t=0;t < 25;t++) {types.push_back(T[t]);}
}
