// The RenderMan Shading Language definition file for Web C Plus Plus
// Generated by Mark Williams <markdjwilliams@hotmail.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Updated 2025 for RenderMan RSL and Open Shading Language (OSL)

#include "langrenderman.h"

LangRenderMan ::LangRenderMan() {

	fill();
	init_switches();

	doPreProc  = Yes;  // #include, #define
	doCinComnt = Yes;  // // line comments
	doBigComnt = Yes;  // /* */ block comments
	doSymbols  = Yes;
}

void LangRenderMan ::fill() {

	// RSL and OSL keywords (combined for .sl file compatibility)
	string K[] = {
		"and",
		"break",
		"closure",
		"continue",
		"displacement",
		"do",
		"else",
		"emit",
		"environment",
		"extern",
		"for",
		"if",
		"illuminance",
		"illuminate",
		"imager",
		"light",
		"not",
		"or",
		"output",
		"public",
		"return",
		"shader",
		"shadow",
		"solar",
		"struct",
		"surface",
		"texture",
		"transformation",
		"uniform",
		"varying",
		"vertex",
		"void",
		"volume",
		"while",
	};
	for(int k=0;k < 34;k++) {keys.push_back(K[k]);}

	// RSL and OSL data types
	string T[] = {
		"color",
		"float",
		"int",
		"matrix",
		"normal",
		"point",
		"string",
		"vector",
	};
	for(int t=0;t < 8;t++) {types.push_back(T[t]);}
}
