// The ObjectiveC Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langobjc.h"

LangObjectiveC ::LangObjectiveC() {

	fill();
	init_switches();

	doSymbols  = Yes;
	doLabels   = Yes;
	doPreProc  = Yes;
	doBigComnt = Yes;
	doCinComnt = Yes;
}

void LangObjectiveC ::fill() {

	// Objective-C keywords (modern, through Xcode 16 / Clang 18)
	// Note: C keywords are inherited from LangC
	string K[] = {
		"@autoreleasepool",
		"@available",
		"@catch",
		"@class",
		"@compatibility_alias",
		"@defs",
		"@dynamic",
		"@encode",
		"@end",
		"@finally",
		"@implementation",
		"@import",
		"@interface",
		"@optional",
		"@package",
		"@private",
		"@property",
		"@protected",
		"@protocol",
		"@public",
		"@required",
		"@selector",
		"@synchronized",
		"@synthesize",
		"@throw",
		"@try",
		"NO",
		"Nil",
		"YES",
		"nil",
		"self",
		"super",
	};
	for(int k=0;k < 32;k++) {keys.push_back(K[k]);}

	// Objective-C types
	string T[] = {
		"BOOL",
		"CGFloat",
		"CGPoint",
		"CGRect",
		"CGSize",
		"Class",
		"IMP",
		"NSArray",
		"NSBundle",
		"NSData",
		"NSDate",
		"NSDictionary",
		"NSError",
		"NSInteger",
		"NSMutableArray",
		"NSMutableDictionary",
		"NSMutableSet",
		"NSMutableString",
		"NSNotification",
		"NSNotificationCenter",
		"NSNumber",
		"NSObject",
		"NSSet",
		"NSString",
		"NSTimeInterval",
		"NSUInteger",
		"NSURL",
		"SEL",
		"bycopy",
		"byref",
		"id",
		"in",
		"inout",
		"instancetype",
		"nonnull",
		"null_resettable",
		"null_unspecified",
		"nullable",
		"oneway",
		"out",
	};
	for(int t=0;t < 40;t++) {types.push_back(T[t]);}
}
