/* webcpp - html_writer.cpp
 * Copyright (C)2026 Jeffrey Bakker
   ___________________________________ .. .
 */

#include "html_writer.h"
#include "cffile.h"
#include "defsys.h"
#include "engine_options.h"
#include "theme.h"

#include <cstdlib>

using std::string;

void HtmlWriter::writeDocumentStart(std::shared_ptr<CFfile> io, Theme &theme,
                                    const EngineOptions &options,
                                    const string &name) {

    string gen;
    string style;
    string openht;

    string ImgPath;
    string CssFile;
    string Path;
    int dir_idx;

    gen = R"(<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<!--
Syntax highlighting generated by Web C Plus Plus software v0.9.0
Webcpp 0.8.4 and older Copyright (C)2001 - 2004 Jeffrey Bakker under the GNU GPL
Webcpp 0.9.0 and newer Copyright (C)2026 Jeffrey Bakker under the MIT License
Get webcpp at http://webcpp.sf.net
-->

)";

    if (theme.getImageFile() != "\0") {

        string CopyCmd = COPY;

        ImgPath = theme.getImageFile();
        dir_idx = static_cast<int>(io->getStrOf().rfind(DIRECTORY_SLASH));

        if (dir_idx != -1) {

            Path = io->getStrOf().substr(0, dir_idx + 1);

            theme.setImageLeaf();
            CopyCmd +=
                " \"" + ImgPath + "\" \"" + Path + theme.getImageFile() + "\"";
            system(CopyCmd.data());
        }
    }

    // external or embedded stylesheet
    style =
        "<style type=\"text/css\">\n\n" + theme.getCSSdata() + "</style>\n";

    // html snippet or complete html tags
    if (options.htsnip) {

        openht = style;
    } else {
        openht = "<html>\n<head>\n<title>" + name + "</title>\n" + style +
                 "</head>\n<body>\n\n";
    }

    if (io->isOredir()) {

        *io << "Content-Type: text/html\n\n"; // cgi-ready
    }
    *io << gen << openht << "<div class=\"webcpp\">\n<pre>\n\n";
}

void HtmlWriter::writeDocumentEnd(std::shared_ptr<CFfile> io,
                                  const EngineOptions &options) {

    *io << "\n\n</pre>\n";
    *io << "\n</div>\n";
    if (!options.htsnip) {
        *io << "\n\n</body>\n</html>\n";
    }
}
